version: '3'

services:
  mongodb-bigdata:
    image: mongo:latest
    hostname: bigdata_mongodb
    volumes:
      - dbdata:/data/db
    networks:
      - bigdata-network
    ports:
      - '27017:27017'

  flask-app:
    build: flask/.
    command: python -u flask/app.py
    volumes:
      - ./:/flask
    depends_on:
      - mongodb-bigdata
    networks:
      - bigdata-network
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb://bigdata_mongodb:27017/

volumes:
  dbdata:

networks:
  bigdata-network:
    driver: bridge